services:
  container:
    build:
      context: ./container
    ports:
      - "3000:3000"
    networks:
      - frontend

  teddy-frontend-react:
    build:
      context: ./app
    ports:
      - "3001:3001"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge